---
# yamllint disable rule:line-length
AWSTemplateFormatVersion: "2010-09-09"

Description: |
  Cloudformation template for provisioning a MemoryDB cluster

Parameters:
  Name:
    Type: String
    Description: Name of the MemoryDB cluster.

  NodeType:
    Type: String
    Default: "db.r6g.large" # Visit https://aws.amazon.com/memorydb/pricing/#On-Demand_Nodes for the available node types.
    Description: The cluster's on-demand node type.

  Port:
    Type: Number
    Default: 6379 # Default Redis port
    Description: The port used by the cluster.

  SubnetIds:
    Type: CommaDelimitedList
    Default: ""
    Description: A list of VPC subnet IDs for the subnet group.

  SecurityGroupIds:
    Type: CommaDelimitedList
    Default: ""
    Description: A list of security group names to associate with this cluster.

  ShardCount:
    Type: Number
    Default: 1
    Description: The number of shards in the cluster.

  ReplicaPerShardCount:
    Type: Number
    Default: 1
    Description: The number of replicas to apply to each shard.

Conditions:
  UserProvidedSubnetIds: !Not # Checks whether 'SubnetIds' has been set or not.
    - !Equals
      - !Join ["", !Ref SubnetIds]
      - ""
  UserProvidedSecurityGroupIds:
    !Not # Checks whether 'SecurityGroupIds' has been set or not.
    - !Equals
      - !Join ["", !Ref SecurityGroupIds]
      - ""

Resources:
  # Specifies a cluster. All nodes in the cluster run the same protocol-compliant engine software.
  Cluster:
    Type: AWS::MemoryDB::Cluster
    Properties:
      ACLName: !Ref Acl
      AutoMinorVersionUpgrade: true
      ClusterName: !Ref Name
      FinalSnapshotName: !Join ["-", [!Ref Name, "final-snapshot"]]
      NodeType: !Ref NodeType
      NumReplicasPerShard: !Ref ReplicaPerShardCount
      NumShards: !Ref ShardCount
      Port: !Ref Port
      SubnetGroupName: !If [
          UserProvidedSubnetIds, # Conditional
          !Join ["-", [!Ref Name, "subnetgroup"]], # If true
          !Ref AWS::NoValue, # If false
        ]
      SecurityGroupIds: !If [
          UserProvidedSecurityGroupIds, # Conditional
          !Ref SecurityGroupIds, # If true
          !Ref AWS::NoValue, # If false
        ]
      TLSEnabled: true
      SnapshotRetentionLimit: 5
      SnapshotWindow: 03:00-05:00 # UTC
      SnsTopicArn: !Ref ClusterEventsTopic
      SnsTopicStatus: active
    DependsOn: ClusterEventsTopic # We need an active SNS topic to send MemoryDB events to.

  # Collection of subnets that you can designate for your clusters running in a VPC.
  SubnetGroup:
    Type: AWS::MemoryDB::SubnetGroup
    Condition: UserProvidedSubnetIds # This resource is a conditional create, whether or not the client sets 'SubnetIds'.
    Properties:
      SubnetGroupName: !Join ["-", [!Ref Name, "subnetgroup"]]
      SubnetIds: !Ref SubnetIds

  # Specifies an Access Control List.
  Acl:
    Type: AWS::MemoryDB::ACL
    Properties:
      ACLName: !Join ["-", [!Ref Name, "acl"]]

  ClusterEventsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Join ["-", [!Ref Name, "events"]]

Outputs:
  ClusterArn:
    Description: Arn of the MemoryDB cluster.
    Value: !GetAtt Cluster.Arn

  ClusterAddress:
    Description: The address of the cluster's configuration endpoint.
    Value: !GetAtt Cluster.ClusterEndpoint.Address

  ClusterPort:
    Description: The port used by the cluster configuration endpoint.
    Value: !GetAtt Cluster.ClusterEndpoint.Port

  ClusterStatus:
    Description: The status of the cluster. For example, 'available', 'updating' or 'creating'.
    Value: !GetAtt Cluster.Status
