---
# yamllint disable rule:line-length
AWSTemplateFormatVersion: "2010-09-09"

Description: |
  Example Cloudformation template for provisioning a MemoryDB cluster using a nested stack.

Parameters:
  MemoryDbTemplateUrl:
    Type: String
    Default: "https://aws-memorydb-cf-template.s3.eu-central-1.amazonaws.com/memorydb.yaml"
    Description: This points to the MemoryDB nested stack template residing in Amazon S3.

Resources:
  MemoryDBCluster:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref MemoryDbTemplateUrl
      TimeoutInMinutes: 2
      Parameters:
        Name: !Join ["-", ["test", "example", "db"]]
        NodeType: db.r6g.large
